# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [10]:
z = np.arange( 10, 51 )
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [11]:
print(np.flip(z))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [13]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [12]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [16]:
x = np.random.random((3,3,3))
print(x)

[[[0.79487731 0.96187724 0.1860613 ]
  [0.22346286 0.38301961 0.54218615]
  [0.37864037 0.02871068 0.67000491]]

 [[0.05401304 0.00205299 0.20522097]
  [0.69290068 0.31233506 0.24192019]
  [0.51893511 0.5547636  0.98267055]]

 [[0.52537598 0.73815775 0.83501367]
  [0.78893486 0.1794979  0.0843233 ]
  [0.31439899 0.20552608 0.12901921]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [17]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.14707701 0.00808758 0.01430647 0.80606174 0.91979799 0.77577713
  0.11384342 0.59797343 0.13474714 0.48287658]
 [0.45258241 0.05544809 0.34546802 0.96211655 0.32366029 0.49040508
  0.73218221 0.3773424  0.69012722 0.95710092]
 [0.29127426 0.34971384 0.01611832 0.49916778 0.46082579 0.16223709
  0.29580458 0.5486532  0.09689485 0.35158398]
 [0.79760996 0.34215359 0.92200874 0.01730954 0.38128988 0.13498816
  0.30553553 0.43263622 0.99456049 0.57833633]
 [0.06692895 0.3056578  0.36976949 0.64233498 0.55359849 0.19414217
  0.86412539 0.19687689 0.78065917 0.03585383]
 [0.77416377 0.19149148 0.83940373 0.58029653 0.57347197 0.29787762
  0.47615616 0.95187618 0.22763891 0.31554527]
 [0.34051322 0.40080257 0.72475424 0.21252505 0.09108897 0.3830197
  0.71562123 0.09896121 0.28607067 0.21602278]
 [0.71036799 0.79871887 0.24075277 0.6502494  0.99080068 0.80831351
  0.88669675 0.62384713 0.63535468 0.92452491]
 [0.42283868 0.57747254 0.67213898 0.98866184 0.63577984 0.85271389
  0.26870101 

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [33]:
x = np.zeros((5,5))
d = np.array([1,2,3,4])
x = np.diag(d,-1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)