# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [10]:
z = np.arange( 10, 51 )
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [11]:
print(np.flip(z))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [13]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [12]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [16]:
x = np.random.random((3,3,3))
print(x)

[[[0.79487731 0.96187724 0.1860613 ]
  [0.22346286 0.38301961 0.54218615]
  [0.37864037 0.02871068 0.67000491]]

 [[0.05401304 0.00205299 0.20522097]
  [0.69290068 0.31233506 0.24192019]
  [0.51893511 0.5547636  0.98267055]]

 [[0.52537598 0.73815775 0.83501367]
  [0.78893486 0.1794979  0.0843233 ]
  [0.31439899 0.20552608 0.12901921]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [39]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.93993594 0.02369482 0.34506469 0.16058267 0.50775323 0.34635772
  0.17527059 0.10775656 0.22597056 0.15789973]
 [0.3834077  0.67697592 0.10861717 0.04177896 0.72387552 0.75947326
  0.88222348 0.60623271 0.813654   0.60978106]
 [0.02612675 0.96280397 0.73131502 0.45569567 0.66531049 0.94458752
  0.25919161 0.5603647  0.4308999  0.09576127]
 [0.6452443  0.4559136  0.52259761 0.50653398 0.64896595 0.24707371
  0.33075586 0.46755678 0.87881347 0.25075347]
 [0.72042002 0.54825854 0.27923001 0.66274806 0.90455509 0.7125948
  0.99299433 0.27281655 0.11515106 0.77921079]
 [0.22478399 0.83618257 0.04861841 0.96123117 0.61882225 0.15902039
  0.30524107 0.06491065 0.63627188 0.82380249]
 [0.67932313 0.79215925 0.68798018 0.10256269 0.44847675 0.61662445
  0.16609405 0.34223903 0.11283416 0.73560087]
 [0.49344777 0.24266691 0.54568561 0.00977676 0.86015731 0.06838524
  0.14808387 0.12140675 0.70432446 0.69596086]
 [0.22455394 0.68888983 0.77648332 0.50669538 0.46019055 0.89646717
  0.04141946 

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [33]:
x = np.zeros((5,5))
d = np.array([1,2,3,4])
x = np.diag(d,-1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [42]:
x = np.random.rand(5)
s = np.sum(x)
print(type(x))
print(s)

<class 'numpy.ndarray'>
2.074009068959022


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [48]:
x = np.random.rand(5)
print(x)
print(np.mean(x))

[0.5232804  0.31450805 0.91248358 0.37058945 0.77784978]
0.5797422531674133


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [44]:
l = [x for x in range(11)]
print(np.size(l))

11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [46]:
x = np.random.ranf(10)
print(x)

[0.05890443 0.48685708 0.30249824 0.43574878 0.3293589  0.40893729
 0.73838672 0.26531611 0.58522822 0.29047037]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [49]:
a = np.random.rand(5)
b = np.random.rand(5)
print(a == b)

[False False False False False]


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [ ]:
x = 

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)