In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [3]:
rdm_mat = np.random.rand(2,2)
print(rdm_mat)

[[0.89178981 0.40347359]
 [0.57166299 0.08830998]]


Donner le type de la variable rdm_mat

In [4]:
print(rdm_mat.dtype)

float64


Donner la somme des éléments de ce tableau 2D

In [5]:
print(rdm_mat.sum())

1.9552363703812616


Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [6]:
np.max(rdm_mat, axis= 1)

array([0.89178981, 0.57166299])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [7]:
np.max(rdm_mat, axis=0)

array([0.89178981, 0.40347359])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [8]:
print(rdm_mat)
max_rdm = np.array([])

[[0.89178981 0.40347359]
 [0.57166299 0.08830998]]


In [9]:
for cell in rdm_mat:
    max_rdm = np.append(max_rdm, np.max(cell))

In [10]:
print(max_rdm)

[0.89178981 0.57166299]


On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [11]:
rdm_vect = np.random.randn(100)
rdm_vect.shape
print(rdm_vect)

[-1.12546684  0.04494435  0.08877718 -0.5034989   0.26703605 -1.44548844
 -1.77678841 -0.01242099  1.34837713 -0.39106372  0.93718935  1.11981342
  2.04589258 -0.20087062 -0.12667619  1.1394553   1.32219624  1.43330769
  1.16697137  0.55389401 -0.18705909 -0.12543314 -0.33101177  0.71555882
  0.74519895 -0.99957754 -0.50507943  0.23366836 -0.04402261  0.29148544
  0.8268689   0.55091622  0.11786894 -0.31933696 -0.10791838 -2.79851883
  1.03083404  1.2826029   0.36873736  0.56300061  0.07012259  0.10049339
 -0.23286052  1.18030553  0.7178182  -1.21929032 -0.1113409   1.12398327
  1.61952934  0.17464643 -1.3110086  -0.4349315   0.43172449 -2.14738482
 -1.0059449  -0.22614556  0.48369562 -1.15989255  2.16409373 -1.3543334
  0.7663387  -0.72753188 -1.04463519  0.08668232  0.78410266 -1.0908774
 -0.24557657  0.21160655  1.31858465 -1.25999687  0.94338178  1.20393458
  2.17994337  1.3357557  -0.12635971  0.01718148  0.94353148 -0.57841946
 -0.6822964  -0.18230383  0.23667737 -0.43196635  0.3

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [12]:
np.argmax(rdm_vect)

72

Afficher cette valeur 

In [13]:
"1er"
print(np.max(rdm_vect))
"2ème"
print(rdm_vect[np.argmax(rdm_vect)])

2.179943365003701
2.179943365003701


Convertir le vecteur en un tableau 10, 10

In [14]:

m = rdm_vect.reshape(10,10)
print(m)

[[-1.12546684  0.04494435  0.08877718 -0.5034989   0.26703605 -1.44548844
  -1.77678841 -0.01242099  1.34837713 -0.39106372]
 [ 0.93718935  1.11981342  2.04589258 -0.20087062 -0.12667619  1.1394553
   1.32219624  1.43330769  1.16697137  0.55389401]
 [-0.18705909 -0.12543314 -0.33101177  0.71555882  0.74519895 -0.99957754
  -0.50507943  0.23366836 -0.04402261  0.29148544]
 [ 0.8268689   0.55091622  0.11786894 -0.31933696 -0.10791838 -2.79851883
   1.03083404  1.2826029   0.36873736  0.56300061]
 [ 0.07012259  0.10049339 -0.23286052  1.18030553  0.7178182  -1.21929032
  -0.1113409   1.12398327  1.61952934  0.17464643]
 [-1.3110086  -0.4349315   0.43172449 -2.14738482 -1.0059449  -0.22614556
   0.48369562 -1.15989255  2.16409373 -1.3543334 ]
 [ 0.7663387  -0.72753188 -1.04463519  0.08668232  0.78410266 -1.0908774
  -0.24557657  0.21160655  1.31858465 -1.25999687]
 [ 0.94338178  1.20393458  2.17994337  1.3357557  -0.12635971  0.01718148
   0.94353148 -0.57841946 -0.6822964  -0.18230383]
 [

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [15]:
print(np.mean(m, axis=1))

[-0.35055926  0.93911732 -0.0206272   0.15150548  0.3423407  -0.45601275
 -0.1201303   0.5054349  -0.50358833  0.11268712]


Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [16]:
print(np.mean(m, axis=0))

[ 0.08955926  0.30185546  0.37671261 -0.23464339  0.15174198 -0.79125531
  0.07416836  0.15628318  0.61359373 -0.13784821]


Calculer la somme pour chaque ligne (sans boucles)

In [17]:
print(np.sum(m, axis=1))

[-3.5055926   9.39117316 -0.20627201  1.51505479  3.42340701 -4.56012747
 -1.20130303  5.05434898 -5.03588334  1.12687117]


In [18]:
print(np.sum(m, axis=0))

[ 0.8955926   3.01855457  3.76712611 -2.3464339   1.51741975 -7.91255308
  0.74168362  1.56283179  6.13593734 -1.37848213]
